### ISSUE TITLE
Test `test_multiprocessing_slicing` fails on mac and windows 

### ISSUE THREAD

**Issue by bd-assaf** [epic-framework/epic-serialize#1]
This test fails on mac & windows with the following traceback:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/runner/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/runner/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
ModuleNotFoundError: No module named 'serialize'
```
On linux it works, so it's probably a spawn vs. fork issue...
(I thought mac uses fork, same a linux, and that spawn was a windows thing. Isn't it?)
@wild-strudel can you please take a look?

**Comment by bd-assaf** [comment]
Resolved when switching to poetry and new CI.
